package com.qiubw.repository.mapper;

import com.qiubw.domain.entity.Permission;
import com.qiubw.domain.entity.PermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    long countByExample(PermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    int deleteByExample(PermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    int insert(Permission row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    int insertSelective(Permission row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    List<Permission> selectByExample(PermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    Permission selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    int updateByExampleSelective(@Param("row") Permission row, @Param("example") PermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    int updateByExample(@Param("row") Permission row, @Param("example") PermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    int updateByPrimaryKeySelective(Permission row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    int updateByPrimaryKey(Permission row);
}