package com.qiubw.repository.mapper;

import com.qiubw.domain.entity.Role;
import com.qiubw.domain.entity.RoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    long countByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    int deleteByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    int insert(Role row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    int insertSelective(Role row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    List<Role> selectByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    Role selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    int updateByExampleSelective(@Param("row") Role row, @Param("example") RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    int updateByExample(@Param("row") Role row, @Param("example") RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    int updateByPrimaryKeySelective(Role row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    int updateByPrimaryKey(Role row);
}