package com.qiubw.repository.mapper;

import com.qiubw.domain.entity.TicketType;
import com.qiubw.domain.entity.TicketTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TicketTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_type
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    long countByExample(TicketTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_type
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    int deleteByExample(TicketTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_type
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_type
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    int insert(TicketType row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_type
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    int insertSelective(TicketType row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_type
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    List<TicketType> selectByExample(TicketTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_type
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    TicketType selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_type
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    int updateByExampleSelective(@Param("row") TicketType row, @Param("example") TicketTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_type
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    int updateByExample(@Param("row") TicketType row, @Param("example") TicketTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_type
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    int updateByPrimaryKeySelective(TicketType row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_type
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    int updateByPrimaryKey(TicketType row);
}