package com.qiubw.repository.mapper;

import com.qiubw.domain.entity.Ticket;
import com.qiubw.domain.entity.TicketExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TicketMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    long countByExample(TicketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    int deleteByExample(TicketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    int insert(Ticket row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    int insertSelective(Ticket row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    List<Ticket> selectByExampleWithBLOBs(TicketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    List<Ticket> selectByExample(TicketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    Ticket selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    int updateByExampleSelective(@Param("row") Ticket row, @Param("example") TicketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    int updateByExampleWithBLOBs(@Param("row") Ticket row, @Param("example") TicketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    int updateByExample(@Param("row") Ticket row, @Param("example") TicketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    int updateByPrimaryKeySelective(Ticket row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    int updateByPrimaryKeyWithBLOBs(Ticket row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    int updateByPrimaryKey(Ticket row);
}