package com.qiubw.domain.entity;

import java.util.Date;

public class TicketType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_type.id
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_type.name
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    private String name;

    /**
     *
     * This field corresponds to the database column ticket_type.description
     */
    private String description;

    /**
     *
     * This field corresponds to the database column ticket_type.status
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_type.create_time
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_type.update_time
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_type.id
     *
     * @return the value of ticket_type.id
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_type.id
     *
     * @param id the value for ticket_type.id
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_type.name
     *
     * @return the value of ticket_type.name
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_type.name
     *
     * @param name the value for ticket_type.name
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method returns the value of the database column ticket_type.description
     *
     * @return the value of ticket_type.description
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method sets the value of the database column ticket_type.description
     *
     * @param description the value for ticket_type.description
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method returns the value of the database column ticket_type.status
     *
     * @return the value of ticket_type.status
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method sets the value of the database column ticket_type.status
     *
     * @param status the value for ticket_type.status
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_type.create_time
     *
     * @return the value of ticket_type.create_time
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_type.create_time
     *
     * @param createTime the value for ticket_type.create_time
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_type.update_time
     *
     * @return the value of ticket_type.update_time
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_type.update_time
     *
     * @param updateTime the value for ticket_type.update_time
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}