package com.qiubw.domain.entity;

import java.util.Date;

public class Ticket {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.id
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.title
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.type_id
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    private Long typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.user_id
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.status
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.create_time
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.update_time
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.content
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.id
     *
     * @return the value of ticket.id
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.id
     *
     * @param id the value for ticket.id
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.title
     *
     * @return the value of ticket.title
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.title
     *
     * @param title the value for ticket.title
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.type_id
     *
     * @return the value of ticket.type_id
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    public Long getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.type_id
     *
     * @param typeId the value for ticket.type_id
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    public void setTypeId(Long typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.user_id
     *
     * @return the value of ticket.user_id
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.user_id
     *
     * @param userId the value for ticket.user_id
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.status
     *
     * @return the value of ticket.status
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.status
     *
     * @param status the value for ticket.status
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.create_time
     *
     * @return the value of ticket.create_time
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.create_time
     *
     * @param createTime the value for ticket.create_time
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.update_time
     *
     * @return the value of ticket.update_time
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.update_time
     *
     * @param updateTime the value for ticket.update_time
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.content
     *
     * @return the value of ticket.content
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.content
     *
     * @param content the value for ticket.content
     *
     * @mbg.generated Fri Mar 20 15:23:08 CST 2026
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}